import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {lineValuesToCodes} from '../src/engine/hexagram.js';import {ganzhiDayFromGregorian,xunVoidFromGanzhi,monthBranchFromDateTime,solarTermBoundary} from '../src/engine/calendar.js';import {relativeFromPalace} from '../src/engine/elements.js';import {returnRelation} from '../src/engine/relations.js';import {resolveUseGod} from '../src/engine/useGod.js';
const here=path.dirname(fileURLToPath(import.meta.url));const read=p=>JSON.parse(fs.readFileSync(path.join(here,'..',p),'utf8'));const assert=(c,m)=>{if(!c)throw Error(m)};
const xk=read('data/xunkong.json');
assert(ganzhiDayFromGregorian('2026-08-09').ganzhi==='乙卯','2026-08-09 應為乙卯');
assert(ganzhiDayFromGregorian('2026-08-10').ganzhi==='丙辰','2026-08-10 應為丙辰');
assert(ganzhiDayFromGregorian('2026-08-11').ganzhi==='丁巳','2026-08-11 應為丁巳');
const liqiu=solarTermBoundary(2026,8);
assert(liqiu.name==='立秋'&&liqiu.branch==='申','8 月節氣應為立秋、申月');
const localText=utcMs=>{const d=new Date(utcMs+480*60000);return [d.toISOString().slice(0,10),d.toISOString().slice(11,16)]};
const [beforeDate,beforeTime]=localText(liqiu.utcMs-60000),[afterDate,afterTime]=localText(liqiu.utcMs+60000);
assert(monthBranchFromDateTime(beforeDate,beforeTime).branch==='未','立秋前一分鐘應為未月');
assert(monthBranchFromDateTime(afterDate,afterTime).branch==='申','立秋後一分鐘應為申月');
assert(monthBranchFromDateTime('2026-08-11','12:00').branch==='申','8/11 立秋後應為申月');
assert(xunVoidFromGanzhi('丁巳',xk).voidBranches.join('')==='子丑','丁巳旬空應子丑');
assert(lineValuesToCodes([7,7,7,7,7,7]).originalCode==='111111','全陽應乾');
assert(lineValuesToCodes([9,7,7,7,7,7]).changedCode==='011111','初爻老陽應翻陰');
assert(relativeFromPalace('金','木')==='妻財','金剋木為妻財');
assert(returnRelation('木','水')==='回頭生','木變水：水回頭生木');
const configuredUse=resolveUseGod([{relative:'兄弟',moving:false,isShi:false,strength:{score:0}}],{categoryId:'custom',manualRelative:'',questionCategories:{version:'test',categories:[{id:'custom',primary:['兄弟']}]}});
assert(configuredUse.primary?.relative==='兄弟'&&configuredUse.ruleVersion==='test','用神應由分類規則資料驅動');
console.log('OK engine.test.mjs');
